print("Mathematical Operations")

import numpy as np
import math as m
print("Trigonometric functions\n")

arr1 = np.array([0,90,120,180,m.pi,1])
sin = np.sin(arr1)
cos = np.cos(arr1)
tan = np.tan(arr1)
# inv_sin = np.arcsin(arr1)
# inv_cos = np.arccos(arr1)
# inv_tan = np.arctan(arr1)
radians = np.radians(arr1)
sinh = np.sinh(arr1)
cosh = np.cosh(arr1)
tanh = np.tanh(arr1)
# inv_sinh = np.arcsinh(arr1)
# inv_cosh = np.arccosh(arr1)
# inv_tanh = np.arctanh(arr1)

print(f'Sin function : {sin}')
print(f'Cosin function : {cos}')
print(f'Tangent function : {tan}')
# print(f'Inverse of sine function : {inv_sin}')
# print(f'Inverse of cosin function : {inv_cos}')
# print(f'Inverse of tangent function : {inv_tan}')
print(f'Hyperbolic sine : {sinh}')
print(f'Hyperbolic cosine : {cosh}')
print(f'Hyperbolic tangent : {tanh}')
# print(f'Inverse Hyperbolic sine : {inv_sinh}')
# print(f'Inverse Hyperbolic cosine : {inv_cosh}')
# print(f'Inverse Hyperbolic tangent : {inv_tanh}')
print(f'Randians : {radians}')
